-- Create database pedb
CREATE DATABASE IF NOT EXISTS pedb;

/*
   Create table study
   table for information of studies generating 
   the datasets
*/
CREATE TABLE IF NOT EXISTS study (
-- study-id: unique identifier for each study
    study_id SERIAL PRIMARY KEY,
-- study-name: max length 25
    study_name VARCHAR(25) NOT NULL,
-- study-description: max length 100
    study_description TEXT,
-- study-date: publication date of the study
    study_pub_date DATE
);

/* 
   Create table cell-line
    table for information of each cell line
*/
CREATE TABLE IF NOT EXISTS cell_line (
-- cell-line-id: unique identifier for each cell line
    cell_line_id SERIAL PRIMARY KEY,
-- cell-line-name: max length 25
    cell_line_name VARCHAR(25) NOT NULL,
-- cell-line-description: max length 100
    cell_line_description TEXT
);

CREATE TABLE IF NOT EXISTS prime_editor (
-- pe-id: unique identifier for each prime editor
    pe_id SERIAL PRIMARY KEY,
-- pe-name: max length 25
    pe_name VARCHAR(25) NOT NULL,
-- pe-description: max length 100
    pe_description TEXT
);

/* 
   Create table dataset
   table for information of each dataset
   generated by a study
*/
CREATE TABLE IF NOT EXISTS dataset (
-- dataset-id: unique identifier for each dataset
    dataset_id SERIAL PRIMARY KEY,
-- study-id: foreign key to study table
    study_id INT NOT NULL,
-- pe-version, foreign key to prime_editor table
    pe_id INT NOT NULL,
-- cell-line-id: foreign key to cell_line table
    cell_line_id INT NOT NULL,
-- study-type: max length 10, in-vitro, in-vivo, library, ex-vivo etc
    study_type VARCHAR(10),
    FOREIGN KEY (study_id) REFERENCES study (study_id),
    FOREIGN KEY (pe_id) REFERENCES prime_editor (pe_id),
    FOREIGN KEY (cell_line_id) REFERENCES cell_line (cell_line_id)
);

/*
    Entry table, storing the editing result at each target loci
*/
CREATE TABLE IF NOT EXISTS entry (
-- entry-id: unique identifier for each entry
    entry_id SERIAL PRIMARY KEY,
-- dataset-id: foreign key to dataset table
    dataset_id INT NOT NULL,
-- target-loci-size: size of the target loci
    target_loci_size INT NOT NULL,
-- target-loci-sequence-wt: wild type sequence of the target loci
    target_loci_sequence_wt TEXT NOT NULL,
-- target-loci-sequence-edited: edited sequence of the target loci
    target_loci_sequence_edited TEXT NOT NULL,
-- target-loci-editing-score: editing score of the target loci
    target_loci_editing_rate FLOAT NOT NULL,
-- target-loci-editing-score-normalized: whether the editing score is normalized with 
-- background editing rate
    target_loci_editing_rate_normalized BOOLEAN NOT NULL DEFAULT FALSE,
-- target-loci-editing-rate-background: background editing rate of the target loci
    target_loci_editing_rate_background FLOAT,
-- protospacer-start: start position of the protospacer
    protospacer_start INT NOT NULL,
-- protospacer-end: end position of the protospacer
    protospacer_end INT NOT NULL,
-- pbs-start: start position of the pbs
    pbs_start INT NOT NULL,
-- pbs-end: end position of the pbs
    pbs_end INT NOT NULL,
-- lha-start: start position of the left homology arm
    lha_start INT NOT NULL,
-- lha-end: end position of the left homology arm
    lha_end INT NOT NULL,
-- rha-start-wt: start position of the right homology arm
    rha_start INT NOT NULL,
-- rha-end-wt: end position of the right homology arm
    rha_end INT NOT NULL,
-- rha-start-edited: start position of the right homology arm
    rha_start_edited INT NOT NULL,
-- rha-end-edited: end position of the right homology arm
    rha_end_edited INT NOT NULL
);
