/** Hover help text for the Add Model upload form (maps to manifest.yaml fields). */

export const PLUGIN_FORM_HINTS = {
  name: 'Unique plugin slug (lowercase letters, digits, underscores). Must match the plugin directory name and cannot collide with built-in models like deepprime.',
  version: 'Semantic version string stored in manifest.yaml (e.g. 0.1.0).',
  displayName: 'Human-readable name shown in Train, Benchmark, and GET /models.',
  authors: 'Comma-separated list or JSON array of contributor names for the manifest.',
  description: 'Short summary of the model; stored in manifest.yaml and shown in the model catalog.',
  wrapperClass: 'Python class name in wrapper.py that subclasses BasePEModel (e.g. MyModelWrapper). PE Ensemble imports this class at activation.',
  weightFormat: 'Registry format tag for saved weights (e.g. deepprime_ensemble, dummy_state_dict). Returned by save_to_registry and stored in weight manifests.',
  convertEntrypoint: 'Function name in convert.py that PE-DB calls to map standardized rows to model columns (default: convert).',
  peDbFormat: 'format= value for PE-DB exports. Defaults to the plugin name if omitted. Use a built-in format only if you skip a custom convert.py.',
  outputColumns: 'Comma-separated columns convert.py must produce. Validation checks they exist and are non-empty.',
  requiredStdColumns: 'Standardized columns your convert.py expects from PE-DB before conversion.',
  labelColumn: 'Ground-truth efficiency column in converted data (used by evaluate smoke tests).',
  hyperparameters: 'Declared training hyperparameters for the manifest and Train UI (name, type, default per row).',
  hyperparameterName: 'Hyperparameter key passed to wrapper.train() (e.g. epochs, learning_rate).',
  hyperparameterType: 'JSON type hint for the UI: int, float, string, or bool.',
  hyperparameterDefault: 'Default value suggested in the Train page when this model is selected.',
  weightMetadata: 'Optional entries for shipped pretrained weights (id + notes). Files are uploaded separately below.',
  weightId: 'Directory name under weights/<id>/ inside the plugin bundle and the weight set id in the registry.',
  weightNotes: 'Optional description shown in the weight catalog.',
  useZipBundle: 'Upload a single zip containing manifest.yaml, convert.py, wrapper.py, and optional weights/ instead of individual files.',
  replaceExisting: 'Overwrite a pending or rejected plugin with the same name. Active plugins must be deleted first.',
  bundleZip: 'Zip archive of the full plugin directory layout. Paths must not contain .. or absolute prefixes.',
  convertFile: 'Python module PE-DB loads to convert standardized exports into your model input columns.',
  wrapperFile: 'Python module defining your BasePEModel wrapper (train, evaluate, predict, save_to_registry).',
  weightFileUpload: 'Optional pretrained artifact copied into weights/<weight id>/ when uploading (e.g. weights.txt or a checkpoint file).',
  weightIdUpload: 'Registry id for the optional weight file; must match a weight metadata id if both are provided.',
} as const
